var typeLabels = { medical:"醫療", life:"壽險", cancer:"癌症", accident:"意外", longtermcare:"長照", savings:"儲蓄", investment:"投資型" };
var statusLabels = { active:"有效", paidup:"繳清", surrendered:"解約", matured:"滿期", inactive:"停效" };
var routeLabels = { dashboard:"Dashboard", "need-calculator":"保額需求", "health-check":"保單健檢", irr:"IRR 試算", compare:"保單比較", retirement:"退休模擬", scenario:"情境模擬", "premium-analysis":"保費分析", family:"家庭模式", settings:"設定" };
var routes = Object.keys(routeLabels);
function createSummaryCard(label,value,sub){ return '<section class="card"><span class="muted">'+label+'</span><strong>'+value+'</strong>'+(sub?'<small>'+sub+'</small>':"")+'</section>'; }
function createChartContainer(title,id){ return '<section class="panel"><div class="panel-title"><h2>'+title+'</h2></div><canvas id="'+id+'" class="chart"></canvas></section>'; }
function createPolicyCard(p){ return '<section class="card"><strong>'+escapeHtml(p.name)+'</strong><span class="muted">'+escapeHtml(p.company)+' / '+(typeLabels[p.type]||p.type)+'</span><span>'+money(p.annualPremium)+' / '+money(p.coverage)+'</span></section>'; }
function createModal(title, body){ document.getElementById("modalRoot").innerHTML='<div class="modal-backdrop" onclick="closeModal(event)"><section class="modal"><div class="panel-title"><h2>'+title+'</h2><button class="btn ghost" onclick="closeModal(event)">關閉</button></div>'+body+'</section></div>'; }
function closeModal(e){ if(e) e.stopPropagation(); document.getElementById("modalRoot").innerHTML=""; }
function createToast(text){ var t=document.getElementById("toast"); t.textContent=text; t.classList.remove("hidden"); clearTimeout(createToast.timer); createToast.timer=setTimeout(function(){t.classList.add("hidden");},2200); }
function panel(title, body){ return '<section class="panel"><div class="panel-title"><h2>'+title+'</h2></div>'+body+'</section>'; }
function input(key,label,suffix){ return '<label class="field">'+label+'<div class="control"><input type="number" value="'+profile[key]+'" onchange="setProfile(\''+key+'\',Number(this.value))"><span class="suffix">'+suffix+'</span></div></label>'; }
function textInput(id,label,value){ return '<label class="field">'+label+'<input id="'+id+'" value="'+escapeHtml(value||"")+'"></label>'; }
function escapeHtml(s){ return String(s).replace(/[&<>"']/g,function(m){ return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]; }); }
function renderNav(){ document.getElementById("nav").innerHTML = routes.map(function(id){ return '<button class="nav-btn '+(id===view?'active':'')+'" onclick="showSection(\''+id+'\')">'+routeLabels[id]+'</button>'; }).join(""); document.getElementById("pageTitle").textContent = routeLabels[view]; }
function renderDashboard(){
  var coverage=calculateCoverage(), totalCoverage=Object.keys(coverage).reduce(function(s,k){return s+coverage[k];},0), avgIrr=policies.reduce(function(s,p){return s+Number(p.irr||0);},0)/Math.max(1,policies.length), score=calculateInsuranceScore(), pressure=totalPremium()/Math.max(1,profile.annualIncome)*100;
  section("dashboard").innerHTML='<section class="grid grid6">'+createSummaryCard("總年保費",money(totalPremium()))+createSummaryCard("總保障額",money(totalCoverage))+createSummaryCard("平均 IRR",avgIrr.toFixed(2)+"%")+createSummaryCard("保單數量",policies.length)+createSummaryCard("家庭成員數",familyMembers.length)+createSummaryCard("保費壓力",pct(pressure))+'</section><section class="grid grid3">'+createSummaryCard("醫療保障",money(coverage.medical||0))+createSummaryCard("壽險保障",money(coverage.life||0))+createSummaryCard("Insurance Score",score.total+" / 100")+'</section><section class="grid grid2">'+createChartContainer("保障分布 Pie Chart","coveragePie")+createChartContainer("Insurance Score Radar Chart","coverageRadar")+createChartContainer("年度保費 Line / Area Chart","premiumLine")+createChartContainer("保費比較 Bar Chart","premiumBar")+'</section>';
}
function renderNeed(){
  var n=calculateInsuranceNeed(), a=calculateAllocation(), risk=Math.min(100, Math.round(totalPremium()/Math.max(1,profile.annualIncome)*1000));
  section("need-calculator").innerHTML='<section class="grid cols">'+panel("輸入",input("age","年齡","歲")+input("annualIncome","年收入","元")+input("mortgage","房貸","元")+input("childrenCount","小孩數","人")+input("monthlyExpense","每月支出","元")+'<label class="check"><input type="checkbox" '+(profile.hasChild?'checked':'')+' onchange="setProfile(\'hasChild\',this.checked)">有家庭責任</label>')+'<div class="grid"><section class="grid grid4">'+createSummaryCard("壽險需求",money(n.lifeInsuranceNeed))+createSummaryCard("醫療預備金",money(n.medicalReserve))+createSummaryCard("緊急預備金",money(n.emergencyFund))+createSummaryCard("風險分數",risk+" / 100")+'</section>'+createChartContainer("需求雷達","needRadar")+panel("建議摘要",'<p class="notice">優先補足壽險家庭責任，再配置醫療與六個月緊急預備金。建議保費配置：醫療 '+a.medical+'%、壽險 '+a.life+'%、意外 '+a.accident+'%。</p>'+createChartContainer("保費配置 Pie Chart","allocationPie"))+'</div></section>';
}
function renderHealth(){
  var issues=calculateHealthCheck(), score=calculateInsuranceScore();
  section("health-check").innerHTML='<section class="grid cols">'+panel("保單管理",policyForm())+'<div class="grid"><section class="grid grid3">'+createSummaryCard("Insurance Score",score.total+" / 100")+createSummaryCard("年保費負擔",pct(totalPremium()/Math.max(1,profile.annualIncome)*100))+createSummaryCard("保單數",policies.length)+'</section>'+panel("健檢結果",issues.map(function(i){return '<p class="notice '+i.level+'">'+i.text+'</p>';}).join(""))+createChartContainer("保障雷達","healthRadar")+policyTable(true)+'</div></section>';
}
function renderIrr(){
  var p=selectedIrrPolicy(), flows=calculateCashflow(p), rate=calculateIRR(flows), be=calculateBreakEvenYear(flows);
  section("irr").innerHTML='<section class="grid grid3">'+createSummaryCard("IRR",(rate*100).toFixed(2)+"%")+createSummaryCard("回本年",be ? "第 "+be+" 年" : "未回本")+createSummaryCard("總繳保費",money(calculateTotalPremium(flows)))+'</section>'+panel("選擇保單",policySelect("irrPolicy",p.id,"render()"))+createChartContainer("現金流 Bar Chart","cashflowChart")+panel("現金流資料",cashflowTable(flows));
}
function renderCompare(){ section("compare").innerHTML=policyTable(false)+createChartContainer("保單比較 Radar Chart","compareRadar"); }
function renderRetirement(){ var r=calculateRetirement(); section("retirement").innerHTML='<section class="grid cols">'+panel("退休條件",input("age","年齡","歲")+input("retireAge","退休年齡","歲")+input("monthlyExpense","每月支出","元")+input("inflationRate","通膨率","%")+input("returnRate","投資報酬率","%"))+'<div class="grid"><section class="grid grid2">'+createSummaryCard("退休缺口",money(r.gap))+createSummaryCard("所需退休資產",money(r.requiredAssets))+'</section>'+createChartContainer("資產成長曲線","retirementLine")+'</div></section>'; }
function renderScenario(){ var n=calculateInsuranceNeed(); section("scenario").innerHTML=panel("情境",'<section class="grid grid5"><button class="btn secondary" onclick="applyScenario(\'marriage\')">結婚</button><button class="btn secondary" onclick="applyScenario(\'child\')">生小孩</button><button class="btn secondary" onclick="applyScenario(\'house\')">買房</button><button class="btn secondary" onclick="applyScenario(\'incomeDown\')">收入下降</button><button class="btn secondary" onclick="applyScenario(\'earlyRetire\')">提前退休</button></section>')+'<section class="grid grid4">'+createSummaryCard("壽險需求",money(n.lifeInsuranceNeed))+createSummaryCard("緊急預備金",money(n.emergencyFund))+createSummaryCard("保費壓力",pct(totalPremium()/Math.max(1,profile.annualIncome)*100))+createSummaryCard("家庭風險",profile.hasChild ? "需保障" : "低")+'</section>'; }
function renderPremium(){ section("premium-analysis").innerHTML=createChartContainer("各年齡保費 / 長期保費壓力 / 保費成長","premiumGrowth")+policyTable(false); }
function renderFamily(){
  var totalIncome=familyMembers.reduce(function(s,m){return s+Number(m.annualIncome||0);},0), totalExpense=familyMembers.reduce(function(s,m){return s+Number(m.monthlyExpense||0);},0);
  section("family").innerHTML='<section class="grid cols">'+panel("新增家庭成員",familyForm())+'<div class="grid"><section class="grid grid3">'+createSummaryCard("家庭總保費",money(totalPremium()))+createSummaryCard("家庭總保障",money(Object.values(calculateCoverage()).reduce(function(s,v){return s+v;},0)))+createSummaryCard("家庭月支出",money(totalExpense))+'</section>'+createChartContainer("家庭收入 Bar Chart","familyBar")+familyTable()+'</div></section>';
}
function renderSettings(){ section("settings").innerHTML=panel("工作區",'<div class="split"><button class="btn" onclick="exportWorkspace()">匯出完整工作區</button><button class="btn secondary" onclick="document.getElementById(\'importJson\').click()">匯入完整工作區</button><button class="btn ghost" onclick="clearWorkspace()">清除並重設</button></div>')+panel("主題",'<div class="split"><button class="btn secondary" onclick="setTheme(\'system\')">系統</button><button class="btn secondary" onclick="setTheme(\'light\')">Light</button><button class="btn secondary" onclick="setTheme(\'dark\')">Dark</button></div>')+panel("提醒",'<p class="notice">Notification API 可提供保單到期、保費與續保提醒。提醒狀態：'+(workspace.settings.notifications?'已啟用':'未啟用')+'</p><button class="btn" onclick="enableNotifications()">啟用提醒</button>'); }
